---
# Create DNS Token
- block:
    - name: Create Consul Default Token only if it doesn't exist
      ansible.builtin.shell:
        cmd: 'consul acl token create -http-addr={{consul_address}}:8500 -description "Default Token used for DNS" -policy-name dns-policy -secret={{consul_acl_default_token}} -token={{ consul_acl_bootstrap_token }}'
      register: consul_acl_default_token_read_result
      # Only error out if the error is something else apart from the token already being existing.
      failed_when:
        - consul_acl_default_token_read_result.rc != 0
        - '"Invalid Token: SecretID is already in use" not in consul_acl_default_token_read_result.stderr'

  when:
    - consul_bootstrap_node
  run_once: true

# Create Agent Token
- block:
    - name: Create Consul Agent Token only if it doesn't exist
      ansible.builtin.shell:
        cmd: 'consul acl token create -http-addr={{consul_address}}:8500 -description "Agent Token used for interserver" -policy-name agent-policy -secret={{consul_acl_agent_token}} -token={{ consul_acl_bootstrap_token }}'
      register: consul_acl_agent_token_read_result
      # Only error out if the error is something else apart from the token already being existing.
      failed_when:
        - consul_acl_agent_token_read_result.rc != 0
        - '"Invalid Token: SecretID is already in use" not in consul_acl_agent_token_read_result.stderr'

  when:
    - consul_bootstrap_node
  run_once: true

# Create Nomad Agent Token
- block:
    - name: Create Nomad Agent Token only if it doesn't exist
      ansible.builtin.shell:
        cmd: 'consul acl token create -http-addr={{consul_address}}:8500 -description "Token used by Nomad agents" -policy-name nomad-agent-policy -secret={{consul_acl_nomad_agent_token}} -token={{ consul_acl_bootstrap_token }}'
      register: consul_acl_nomad_agent_token_read_result
      # Only error out if the error is something else apart from the token already being existing.
      failed_when:
        - consul_acl_nomad_agent_token_read_result.rc != 0
        - '"Invalid Token: SecretID is already in use" not in consul_acl_nomad_agent_token_read_result.stderr'

  when:
    - consul_bootstrap_node
  run_once: true
