---
# Package installation tasks for Nomad CNI Plugin

- name: Create cni directory
  become: true
  file:
    dest: "/opt/cni/bin"
    state: directory
    owner: "nomad"
    group: "nomad"

- name: Download Nomad CNI
  get_url:
    url: "https://github.com/containernetworking/plugins/releases/download/{{nomad_cni_version}}/cni-plugins-linux-amd64-{{nomad_cni_version}}.tgz"
    dest: "/tmp/cni-plugins.tgz"
    timeout: "60"
  become: false

- name: Unarchive Nomad CNI
  unarchive:
    src: "/tmp/cni-plugins.tgz"
    dest: "/opt/cni/bin"
    remote_src: yes
  become: true
