---
- name: Create configuration
  template:
    src: nomad.hcl.j2
    dest: "/etc/nomad.d/nomad.hcl"
    owner: nomad
    group: nomad
    mode: 0644
  notify:
    - restart nomad


- name: Start Nomad
  service:
    name: nomad
    state: started
    enabled: yes
