---
- name: Create configuration
  template:
    src: nomad.hcl.j2
    dest: "/etc/nomad.d/nomad.hcl"
    owner: nomad
    group: nomad
    mode: 0644
  notify:
    - restart nomad

- block:
  - name: Create ACL Bootstrap Token
    import_tasks: acl_bootstrap.yml
  
  when: nomad_enable_acl

- name: Start Nomad
  service:
    name: nomad
    state: started
    enabled: yes
