---
- name: check if docker_user is set
  assert:
    that:
      - docker_user is defined
      - docker_user | length > 0

- name: check if docker_group is set
  assert:
    that:
      - docker_group is defined
      - docker_group | length > 0

- name: check if docker_compose_version is set
  assert:
    that:
      - docker_compose_version is defined
      - docker_compose_version | length > 0
