- hosts: all
  become: true
  gather_facts: true
  roles:
    - role: docker
      become: true
      docker_compose_version: 1.29.2

    - role: consul
      vars:
        consul_dc: localhashi
        consul_version: 1.12.0-1
        consul_enable_server: true
        consul_enable_acl: false
        consul_encrypt_key: "{{ lookup('env','CONSUL_ENCRYPT_KEY') }}"
        # consul_acl_agent_token: "{{consul_acl_agent_token}}"
        # consul_acl_default_token: "{{consul_acl_default_token}}"
        # consul_acl_nomad_server_token: "{{consul_acl_nomad_server_token}}"
        # consul_acl_nomad_client_token: "{{consul_acl_nomad_client_token}}"

    - role: nomad
      vars:
        nomad_dc: localhashi
        nomad_version: 1.2.6
        nomad_encrypt_key: "{{ lookup('env','NOMAD_ENCRYPT_KEY') }}"
        nomad_enable_server: true
        nomad_enable_client: true
        nomad_enable_acl: false
        # consul_acl_nomad_token: "{{consul_acl_nomad_server_token}}"
